// src/views/NotFound.vue
<template>
  <div class="not-found">
    <v-container class="text-center">
      <v-row justify="center">
        <v-col cols="12" md="8">
          <v-card class="mt-10 pa-5">
            <v-card-title class="text-h3 mb-5">
              404 - Page Not Found
            </v-card-title>

            <v-img
              src="@/assets/not-found.svg"
              alt="Page Not Found"
              max-width="300"
              class="mx-auto mb-5"
            />

            <v-card-text class="text-body-1">
              <p>Sorry, the page you are looking for doesn't exist or has been moved.</p>
            </v-card-text>

            <v-card-actions class="justify-center mt-5">
              <v-btn
                color="primary"
                to="/"
              >
                <v-icon left>
                  mdi-home
                </v-icon>
                Return to Home
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script>
export default {
  name: 'NotFoundView'
}
</script>

<style scoped>
.not-found {
  min-height: 80vh;
}
</style>

// src/pages/NotFound.tsx
import React from 'react';
import { Link } from 'react-router-dom';

const NotFound: React.FC = () => {
  return (
    <div className="min-h-[60vh] flex flex-col items-center justify-center">
      <h1 className="text-6xl font-bold text-primary-600">404</h1>
      <p className="mt-4 text-xl text-gray-600">Page not found</p>
      <p className="mt-2 text-gray-500">
        The page you're looking for doesn't exist or has been moved.
      </p>
      <Link to="/" className="mt-8 btn btn-primary">
        Go back home
      </Link>
    </div>
  );
};

export default NotFound;
